name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages # ✅ This is required for GitHub Pages deployments
    # Job steps
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      # - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      #   with:
      #     install_command: pnpm install # default: npm ci
      #     build_command: pnpm build-storybook # default: npm run build-storybook
      #     path: storybook-static # default: dist/storybook
      #     checkout: false # default: true
